export enum ActivityType {
  Sleep = 'sleep',
  Nap = 'nap',
  Workout = 'workout',
}

// Sport labels for the recording picker — cosmetic only, stored in activity_events.type
// Maps to ActivityType.Workout in the DB sense
export const SPORT_LABELS: string[] = [
  'CrossFit',
  'Cycling',
  'Functional Fitness',
  'HIIT',
  'Running',
  'Swimming',
  'Walking',
  'Weightlifting',
  'Yoga',
  // ── alphabetical below ──
  'Baseball',
  'Basketball',
  'Boxing',
  'Calisthenics',
  'Climbing',
  'Cricket',
  'Dance',
  'Elliptical',
  'Football',
  'Golf',
  'Gymnastics',
  'Handball',
  'Hiking',
  'Hockey',
  'Ice Skating',
  'Jiu-Jitsu',
  'Kayaking',
  'Kickboxing',
  'Lacrosse',
  'Martial Arts',
  'Padel',
  'Paddleboarding',
  'Pickleball',
  'Pilates',
  'Racquetball',
  'Rowing',
  'Rugby',
  'Skiing',
  'Snowboarding',
  'Soccer',
  'Squash',
  'Stretching',
  'Surfing',
  'Tennis',
  'Trail Running',
  'Triathlon',
  'Volleyball',
  'Water Polo',
  'Workout',
  'Wrestling',
];
